### ISSUE TITLE
X1C6 hangs with lenovo-throttling-fix

### ISSUE THREAD

**Issue by krionbsd** [erpalma/lenovo-throttling-fix#43]
I'm using Linux Mint 19 on one of my laptop (X1C6) and after going through all steps and uninstalling thermald, laptop hangs spontaneous during first 2-3 mins after starting, deinstalling throttling fix helps to fix it.

Is it a known issue with Mint?

**Comment by erpalma** [comment]
What do you mean with hang exactly?

**Comment by krionbsd** [comment]
It's unresponsive completely, I only can reboot it

**Comment by krionbsd** [comment]
I forgot to mention, I'm using latest BIOS 1.27 and disabled "Secure Boot" in it.

**Comment by erpalma** [comment]
Uh so it's freezed. Did you enabled undervolting?

**Comment by krionbsd** [comment]
Yes, I've enabled these settings:

[UNDERVOLT]
# CPU core voltage offset (mV)
CORE: -110
# Integrated GPU voltage offset (mV)
GPU: -90
# CPU cache voltage offset (mV)
CACHE: -110
# System Agent voltage offset (mV)
UNCORE: -90
# Analog I/O voltage offset (mV)
ANALOGIO: 0

**Comment by MartinX3** [comment]
And without undervolting you still get the freezing?

**Comment by krionbsd** [comment]
Hmm, that's interesting, it runs fine after removing undervolting settings completely, so any hints about it?

**Comment by DEvil0000** [comment]
your undervolting is definitivly too high. lower the values by about 20.

-------- Ursprüngliche Nachricht --------
Von: Martin Dünkelmann <notifications@github.com> 
Datum: 29.08.2018  19:33  (GMT+01:00) 
An: erpalma/lenovo-throttling-fix <lenovo-throttling-fix@noreply.github.com> 
Cc: Subscribed <subscribed@noreply.github.com> 
Betreff: Re: [erpalma/lenovo-throttling-fix] X1C6 hangs with
  lenovo-throttling-fix (#43) 

And without undervolting you still get the freezing?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/erpalma/lenovo-throttling-fix","title":"erpalma/lenovo-throttling-fix","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/erpalma/lenovo-throttling-fix"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MartinX3 in #43: And without undervolting you still get the freezing?"}],"action":{"name":"View Issue","url":"https://github.com/erpalma/lenovo-throttling-fix/issues/43#issuecomment-417038919"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/erpalma/lenovo-throttling-fix/issues/43#issuecomment-417038919",
"url": "https://github.com/erpalma/lenovo-throttling-fix/issues/43#issuecomment-417038919",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [erpalma/lenovo-throttling-fix] X1C6 hangs with lenovo-throttling-fix (#43)",
"sections": [
{
"text": "",
"activityTitle": "**Martin Dünkelmann**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@MartinX3",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"erpalma/lenovo-throttling-fix\",\n\"issueId\": 43,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"erpalma/lenovo-throttling-fix\",\n\"issueId\": 43\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/erpalma/lenovo-throttling-fix/issues/43#issuecomment-417038919"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 373742679\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by krionbsd** [comment]
ok, thanks for hint, I'll try with -90 and -70 next time.
What surprises me, if I run on battery or AC:

```
sudo rdmsr -f 29:24 -d 0x1a2
20
```

IIRC it should be 15 on battery and 3 on AC.

**Comment by erpalma** [comment]
So you are reading 20 (80 'C) while the script is running?

**Comment by DEvil0000** [comment]
check with `--debug` if it is getting set correct.
After a config change you need to restart the script.

**Comment by krionbsd** [comment]
Yes, I set new values for undervolting like:
```
CORE: -105
GPU: -85
CACHE: -105
UNCORE: -85
ANALOGIO: 0
```
Restarted it:
```
~ systemctl status lenovo_fix.service
● lenovo_fix.service - Stop Intel throttling
   Loaded: loaded (/etc/systemd/system/lenovo_fix.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2018-08-30 11:37:27 CEST; 3min 45s ago
 Main PID: 5074 (python3)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/lenovo_fix.service
           └─5074 /opt/lenovo_fix/venv/bin/python3 /opt/lenovo_fix/lenovo_fix.py
```
But I still get value 10 running rdmst on AC:
```
~ sudo rdmsr -f 29:24 -d 0x1a2              
10
```

**Comment by krionbsd** [comment]
Thank you @DEvil0000 for hints and clarification, I'll try proposed values
